name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 20
          - operating-system: windows-latest
          - npm: 10
        exclude:
          - node-version: 14
          - operating-system: windows-latest
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
