name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact:
        description: Path to the deployable artifact
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: ${{inputs.artifact}}
      - name: Output information
        run: echo "Deploying..."
